### ISSUE TITLE
IndexError: cannot choose from empty sequence

### ISSUE THREAD

**Issue by Door0012** [forteus19/zcb-gui#3]
when i click generate clicks, it says Indexerror: cannot choose from empty sequence

**Comment by forteus19** [comment]
Please send a screenshot

**Comment by Door0012** [comment]
![image](https://user-images.githubusercontent.com/126026266/221248397-bd1c46bb-93c8-4afb-a9a7-e759a7391ddc.png)
ok, when i click the macro, it prases corectly, but in the clickpack theres an error, but i think i should ignore, but the output I do it intho a zcb folder called output and give it a name so it can save but it still get me the error

**Comment by Door0012** [comment]
I use tbot with a macro converter

**Comment by forteus19** [comment]
The problem looks like your clickpack
Send a screenshot of the folder

**Comment by Door0012** [comment]
![image](https://user-images.githubusercontent.com/126026266/221391169-b2ce8d06-1a95-4b9d-a026-5bf721c61482.png)
![image](https://user-images.githubusercontent.com/126026266/221391173-4a5a0608-595b-4987-94de-205cd786aa88.png)

**Comment by Door0012** [comment]
yup, it was a clickpack problem, i need to create a folder called player1 so zcb reads it and i put the clicks, hardclicks in the player1 folder, thanks for help!
