### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by frontrunnin** [forteus19/zcb-gui#4]
Whenever I use zcb it just stays at 0% and says this:
![Screenshot 2023-04-09 09-21-22 (2)](https://user-images.githubusercontent.com/130293657/230775465-ef106e7b-832c-4b58-862a-03d9767586f9.png)
One more thing: I always make sure I have player1 and player2 folders, but it always says "/player1 has no clicks!"
Is there a way to fix these issues? I use TASBot

**Comment by forteus19** [comment]
did you put a clicks folder inside of the player folder

**Comment by frontrunnin** [comment]
I did but I named it "holds" instead of "clicks" so thank you that actually fixed the player1 problem
still have the other problems though

**Comment by forteus19** [comment]
what are the other problems

**Comment by frontrunnin** [comment]
The thing where it gets stuck at 0

**Comment by floams** [comment]
where is the player folder

**Comment by frontrunnin** [comment]
Its right under the name of the click pack
https://user-images.githubusercontent.com/130293657/236918865-621f0ab4-e988-471c-b2e8-4c5939405cea.mp4

**Comment by frontrunnin** [comment]
OH MY GOD ITS FIXED YESSS! IM SO HAPPY HAHAH
