### ISSUE TITLE
Serious error with clickpack

### ISSUE THREAD

**Issue by frontrunnin** [forteus19/zcb-gui#8]
When I select a clickpack (the vladuwka12 clicks), it says this, even though I have a player1 and player2 folder and the files are .wav: 
![screenshot (2)](https://github.com/forteus19/zcb-gui/assets/130293657/2c6617b7-01bd-4d00-8f28-2a2d7bcc0c2a) I need to use this clickpack
Also, when I generate clicks with a different clickpack, the clicks sound really weird and unrealistic, where there is 1 loud normal click and then the rest is just super inaudibly quiet

**Comment by forteus19** [comment]
the clicks and releases folders have to be lowercase

**Comment by forteus19** [comment]
actually the entire clickpack Is formatted incorrectly

**Comment by frontrunnin** [comment]
tysm bro

**Comment by frontrunnin** [comment]
tysm bro

**Comment by frontrunnin** [comment]
so I tried and it actually still doesnt work after i removed capitals and renamed the click and release sounds to 1 and 2, and it still does not work

**Comment by forteus19** [comment]
did you also make the file extensions lowercase?

**Comment by frontrunnin** [comment]
Its fixed, thank you
